export enum USER_ROLES {
  SUPER_ADMIN = "SUPER_ADMIN",
  ADMIN = "ADMIN",
  CONTRIBUTOR = "CONTRIBUTOR",
  USER = "USER",
  GUEST = "GUEST",
}

export enum ACTION_LOGS {
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  REGISTER = "REGISTER",
}
