-- DDL generated by Postico 2.1.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE auth.sessions (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    token_hash text NOT NULL,
    auth_user_id uuid NOT NULL REFERENCES auth.users(id),
    is_revoked boolean DEFAULT false
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX sessions_pkey ON auth.sessions(id uuid_ops);
CREATE INDEX idx_sessions_auth_user_id ON auth.sessions(auth_user_id uuid_ops);