-- DDL generated by Postico 2.1.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE logs.action_logs (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    action text,
    auth_user_id uuid,
    url text,
    request_body jsonb,
    status smallint
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX action_logs_pkey ON logs.action_logs(id uuid_ops);
