-- DDL generated by Postico 2.1.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE logs.error_logs (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    message text,
    status_code smallint,
    request_metadata jsonb,
    response_metadata jsonb,
    method text,
    url text,
    auth_user_id uuid REFERENCES auth.users(id)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX error_logs_pkey ON logs.error_logs(id uuid_ops);
